<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-KVV4E8PT" failures="1" tests="1" name="Test(failed)" time="10.787" errors="0" timestamp="2022-11-02T21:09:20 IST">
  <testcase classname="Amazontestng123.NewTest12" name="a5" time="1.743">
    <failure type="java.lang.AssertionError" message="expected [https://www.amazon.in/events/greatindianfestival?ref_=nav_cs_gb1] but found [https://www.amazon.in/events/greatindianfestival?ref_=nav_cs_gb]">
      <![CDATA[java.lang.AssertionError: expected [https://www.amazon.in/events/greatindianfestival?ref_=nav_cs_gb1] but found [https://www.amazon.in/events/greatindianfestival?ref_=nav_cs_gb]
at Amazontestng123.NewTest12.a5(NewTest12.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- a5 -->
  <testcase classname="Amazontestng123.NewTest12" name="a3" time="0.0">
    <ignored/>
  </testcase> <!-- a3 -->
</testsuite> <!-- Test(failed) -->
